package com.i2iproject.database;

import com.i2iproject.database.models.PasswordChangeAfterLoginCodePersistenceInfo;

public interface PasswordChangeAfterLoginCodePersister {
	public boolean persistPasswordChangeAfterLoginCode(PasswordChangeAfterLoginCodePersistenceInfo passAfterLoginPersistenceInfo);
}
